### ISSUE TITLE
Alpine example

### ISSUE THREAD

**Issue by mkuzmin** [jetbrains-infra/packer-builder-vsphere#181]
Integration tests with Ubuntu installation are too slow.
We need a smaller and faster Linux distribution like Alpine

**Comment by thor** [comment]
Alpine's pretty neat. If you'd like to keep the image fairly straight, it might be best to script [the setup of SSH on Alpine](https://wiki.alpinelinux.org/wiki/Setting_up_a_ssh-server) together with [creating a bootable disk with those modifications already in place](https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-bootable).

If you don't want to use Alpine after all, you could instead use [Ubuntu's minimal CD to boot in and install SSH](https://help.ubuntu.com/community/Installation/MinimalCD). It might be easiest to use it together with a *kickstart* or *preseed* file.

**Comment by arizvisa** [comment]
Ftr, I had success with ttylinux when writing the PACKER_ACC tests for the VMware builder in Packer (https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/step_create_vmx_test.go#L22). I had needed to prove that USB, Sound, and Serial/Parallel ports worked and in order to do this I needed a platform with a short boot-time that I could xfer data from w/o depending on the network. (To do this I used the floppy device to write data to, which will probably change for this particular situation)

One thing that I felt was important was that the distribution was simple, stupid, and was not a moving target. If there is interest in help for this, I don't mind implementing similar logic that I did in Packer for this plugin.

**Comment by mkuzmin** [comment]
Ubuntu mini-CD is small because everything is downloaded from the net. But that makes a build time even worse.

ttylinux is super-fast, but it don't see how can we install `open-vm-tools` there. A part of our tests boots VMs.

**Comment by arizvisa** [comment]
Ahh ok. Gotcha. That's a shame.

Looks like vmware/govmomi is using /toolbox for their system to maybe help reduce external software deps (https://github.com/vmware/govmomi/tree/master/toolbox). It's probably not fully supporting 100% of open-vm-tools, but maybe worth thinking about in the distant future.

**Comment by mkuzmin** [comment]
I've made Alpine example yesterday: https://github.com/jetbrains-infra/packer-builder-vsphere/tree/alpine/examples/alpine
Full provisioning takes 2 minutes.

**Comment by bby-bishopclark** [comment]
I see it at https://github.com/jetbrains-infra/packer-builder-vsphere/tree/master/examples/alpine . 

Woo!  Fantastic base to work from.  Thanks!

**Comment by mkuzmin** [comment]
Yeah, but still it has too much typing in `boot_command`. My integration tests are too flaky.

Maybe `chroot` would work better than reboot in the middle.
