### ISSUE TITLE
Replace Existing Template with Same Name

### ISSUE THREAD

**Issue by alexgaganashvili** [jetbrains-infra/packer-builder-vsphere#50]
Hi,

Could you add a feature allowing replacement of the template if it already exists? It'd be easier than having to delete the template via vsphere client before building a new one.

Thanks

**Comment by alexgaganashvili** [comment]
Just being curious if anyone has seen my feature request yet.
Thanks.

**Comment by mkuzmin** [comment]
I agree such feature would be helpful when you are developing a new template and iterating over it multiple times.
But deleting data is a dangerous action, you may accidentally destroy unrelated VMs.

I don't think we should add this as a permanent parameter in JSON config, but an environment variable would work.

**Comment by alexgaganashvili** [comment]
Yes, an environment variable would work. I agree there's a danger in destroying unrelated VMs. Maybe there's a way to check whether the VM is actually a template and destroy it only if it is. In the worst case, a template - and not a VM - would be lost.

**Comment by mkuzmin** [comment]
by the way, dynamic names would also help here: `"vm_name": "vm-{{timestamp}}"`

**Comment by troxil** [comment]
This would be an excellent feature. Though, should be treated with care. Perhaps a few toggles. Replace, rename or force.

**Comment by mkuzmin** [comment]
Will answer the question from the related issue here
> Unless I can detect the creation of my template that packer just made, then I would prefer if it was handled smartly.

There is [Manifest post-processor](https://www.packer.io/docs/post-processors/manifest.html) for that.

In TeamCity we solved this issue by [another plugin](https://github.com/JetBrains/packer-post-processor-teamcity). Not sure, maybe a similar Ansible plugin is also possible.

**Comment by mkuzmin** [comment]
After some thoughts, I'm going to close this issue.

`{{timestamp}}` works well for testing purposes.
In production such a feature is too dangerous and violates a core idea of immutable infrastructure.

If you have other use cases - please share.

**Comment by sudomateo** [comment]
I think that a proper use case should be using the `-force` option to enable this behavior. This fits with existing use cases. For example, if I was building an artifact using the `virtualbox-iso` builder, I would have to delete the artifacts in the `output-virtualbox-iso` directory before building subsequent artifacts. With the `-force` option it will remove/overwrite those artifacts.

```
➜  packer-poc git:(master) ✗ packer build --help
Usage: packer build [options] TEMPLATE

  Will execute multiple builds in parallel as defined in the template.
  The various artifacts created by the template will be outputted.

Options:

  -color=false               Disable color output (on by default)
  -debug                     Debug mode enabled for builds
  -except=foo,bar,baz        Build all builds other than these
  -only=foo,bar,baz          Build only the specified builds
  -force                     Force a build to continue if artifacts exist, deletes existing artifacts
  -machine-readable          Machine-readable output
  -on-error=[cleanup|abort|ask] If the build fails do: clean up (default), abort, or ask
  -parallel=false            Disable parallelization (on by default)
  -var 'key=value'           Variable for templates, can be used multiple times.
  -var-file=path             JSON file containing user variables.
```

**Comment by stacycarter** [comment]
Yes, I agree, would like to see this feature.  I have this use case as well when using the [still in beta, but hopefully prod soon] vSphere-ISO builder, creating vSphere templates from scratch/ISO.  I would want to recreate the same templates on a regular basis (ie nightly, or weekly...).  

Without this feature in Packer, admins have to write a separate script to delete the old templates in order to replace them.  (In the script I would have to create to do this, I would have it search for a particular vSphere folder, have it look specifically for just templates and only in that folder that match a certain name pattern, and then delete those from disk).

Of course, I'm new to Packer so let me know if I'm missing something.

**Comment by xenithorb** [comment]
A bit odd that `-force` exists in packer for a reason and this plugin doesn't support it

**Comment by mkuzmin** [comment]
done by #186. Thanks, @remijouannet!

**Comment by gstorme** [comment]
This removes the existing before starting to build a new one with the same name, correct?  
Is there a way to build with a temporary name, for example suffixed by timestamp or user defined, and overwrite the template only if the build is successful?

**Comment by nitrocode** [comment]
@gstorme @mkuzmin there can definitely be a best of both worlds. Instead of a `replace` option, how about a `promote` option?

For example, if the template is called `ubuntu_golden` and we have the `promote` option set to `true`, then it could create a temporary name like `ubuntu_{{ timestamp }}`, once it's done, it can rename the old template to `ubuntu_golden_{{ timestamp }}` and the new one can be renamed to `ubuntu_golden`. This will allow us to roll back in case the new template has issues.
